export class EVENT {
  id: number = -1;
  ony: number = 0;
  mc: number = 0;
  bwl: number = 0;
  naxx: number = 0;
  k10: number = 0;
  k40: number = 0;
  es: number = 0;
  zg: number = 0;
  aq20: number = 0;
  aq40: number = 0;
  dmf: string = "";
  madness: number = 0;
  // @Column(name = "madness_boss")
  madnessBoss: string = "";
  pvp: string = "";
  old: number = 0;
  date: string = "";
}
